name: "Deploy to nuget.org"
description: "Deploy to nuget.org"

inputs:
  token:
    description: "The token to use for nuget publishing"
    required: true

runs:
  using: "composite"

  steps:
  - name: Download Artifacts
    uses: actions/download-artifact@v4
    with:
        name: NuGet-Signed
        path: artifacts

  - uses: actions/setup-dotnet@v4
    with:
      dotnet-version: '9.0.x'

  - name: Add Azure DevOps NuGet source
    shell: pwsh
    run: |
        Push-Location $env:RUNNER_TEMP
        dotnet nuget add source https://pkgs.dev.azure.com/uno-platform/1dd81cbd-cb35-41de-a570-b0df3571a196/_packaging/unoplatformdev/nuget/v3/index.json `
            --name "AzureDevOps" `
            --username "az" `
            --password "${{ inputs.token }}" `
            --store-password-in-clear-text
        Pop-Location

  - name: Uno NuGet Feed Push
    shell: pwsh
    env:
      ARTIFACTS_PATH: ${{ github.workspace }}/artifacts
    run: |
        Push-Location $env:RUNNER_TEMP
        dotnet nuget push "$env:ARTIFACTS_PATH/*.nupkg" --source AzureDevOps --api-key az --skip-duplicate
        Pop-Location
