jobs:
- job: Windows

  pool:
    vmImage: 'windows-latest'

  steps:
  - template: build/templates/gitversion-run.yml

  - task: UseDotNet@2
    displayName: 'Use .NET 10 SDK'
    inputs:
      includePreviewVersions: true
      version: 10.x
  
  - script: dotnet workload install wasm-tools wasm-tools-net9
    displayName: Install workloads

  - task: DotNetCoreCLI@2
    inputs:
      command: build      
      projects: MonacoEditorComponent.slnx
      arguments:  -c Release -p:PackageOutputPath=$(build.artifactstagingdirectory)/nuget /bl:$(build.artifactstagingdirectory)/build.binlog 

  - task: PowerShell@2
    displayName: Authenticode Sign Packages
    inputs:
      filePath: build/Sign-Package.ps1
    env:
      SignClientUser: $(SignClientUser)
      SignClientSecret: $(SignClientSecret)
      SignPackageName: "uno.monaco-editor-uwp"
      SignPackageDescription: "uno.monaco-editor-uwp"
      ArtifactDirectory: $(build.artifactstagingdirectory)
    condition: and(succeeded(), not(eq(variables['build.reason'], 'PullRequest')), not(eq(variables['SignClientSecret'], '')), not(eq(variables['SignClientUser'], '')))

  - task: PublishBuildArtifacts@1
    condition: always()
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      ArtifactName: uno-monaco-editor-uwp-drop
      ArtifactType: Container
